tap "buo/cask-upgrade"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mongodb/brew"
brew "bash"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "git"
brew "python"
brew "gnupg"
brew "jenv"
brew "mas"
brew "neofetch"
brew "nmap"
brew "node"
brew "rclone"
brew "speedtest-cli"
brew "telnet"
brew "trash"
brew "tree"
brew "wget"
brew "heroku/brew/heroku"
brew "mongodb/brew/mongodb-community"
cask "1password"
cask "alfred"
cask "altserver"
cask "android-file-transfer"
cask "android-platform-tools"
cask "android-studio"
cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "caldigit-thunderbolt-charging"
cask "carbon-copy-cloner"
cask "cyberduck"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "gitkraken"
cask "google-backup-and-sync"
cask "gpg-suite"
cask "handbrake"
cask "iina"
cask "insync"
cask "intellij-idea"
cask "itsycal"
cask "java11"
cask "jdownloader"
cask "karabiner-elements"
cask "keka"
cask "logitech-camera-settings"
cask "logitech-options"
cask "mactex"
cask "makemkv"
cask "megasync"
cask "microsoft-edge"
cask "minecraft"
cask "mongodb-compass"
cask "monitorcontrol"
cask "nordvpn"
cask "notion"
cask "postman"
cask "rescuetime"
cask "skype"
cask "spotify"
cask "steam"
cask "suspicious-package"
cask "transmission"
cask "tunnelblick-beta"
cask "tuxera-ntfs"
cask "visual-studio-code"
cask "vmware-fusion"
cask "vnc-server"
cask "vnc-viewer"
cask "xquartz"
cask "zoomus"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Cascadea", id: 1432182561
mas "Dark Reader for Safari", id: 1438243180
mas "Debit & Credit", id: 882637653
mas "Hex Fiend", id: 1342896380
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Notability", id: 736189492
mas "OneDrive", id: 823766827
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
