tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "git"
brew "python@3.8"
brew "mackup"
brew "mas"
brew "neofetch"
brew "nmap"
brew "speedtest-cli"
brew "telnet"
brew "trash"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "alfred"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "caprine"
cask "carbon-copy-cloner"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "gimp"
cask "gpg-suite"
cask "handbrake"
cask "iina"
cask "insync"
cask "intellij-idea"
cask "itsycal"
cask "jdownloader"
cask "karabiner-elements"
cask "keka"
cask "logitech-camera-settings"
cask "logitech-options"
cask "macs-fan-control"
cask "mactex-no-gui"
cask "makemkv"
cask "megasync"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "minecraft"
cask "monitorcontrol"
cask "notion"
cask "rescuetime"
cask "skype"
cask "spotify"
cask "steam"
cask "tex-live-utility"
cask "transmission"
cask "tunnelblick-beta"
cask "tuxera-ntfs"
cask "visual-studio-code"
cask "vmware-fusion"
cask "xquartz"
cask "yacreader"
cask "yakyak"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "Debit & Credit", id: 882637653
mas "Hex Fiend", id: 1342896380
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "NordVPN IKE", id: 1116599239
mas "Notability", id: 736189492
mas "OneDrive", id: 823766827
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "Xcode", id: 497799835
